version: "3.8"

services:
  mobile:
    container_name: node-mobile
    image: node:18.0.0-alpine3.15
    tty: true
    working_dir: /home/node/src
    volumes:
      - .:/home/node/src
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # Set your local IP address to connect it to 'expo'.
      # 'ipconfig' or 'hostname -i' to get your local IP.
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOSTNAME}
      - EXPO_CLI_PASSWORD=${EXPO_CLI_PASSWORD}
      - EXPO_CLI_USERNAME=${EXPO_CLI_USERNAME}
    # command:
    #   - "npm i -g expo-cli"
    #   - "npm run start"
