version: "3.8"

services:
  server:
    container_name: node-server
    image: node:18.0.0-alpine3.15
    # tty: true
    working_dir: /home/node/src
    volumes:
      - .:/home/node/src
    ports:
      - "3333:3333"
      - "5555:5555" # prisma studio
    command: "npm run docker:dev"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
